### ISSUE TITLE
Change vp >= 15 to if any(vs) >= 15 in vp2vs.py 

### ISSUE THREAD

**Issue by SeismoFelix** [thurinj/specfem_tomo_helper#3]
The function [vp2vs.py](https://github.com/thurinj/specfem_tomo_helper/blob/main/specfem_tomo_helper/projection/vp2vs.py#L13) yields an ambiguity error: 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
I guess this is because similarly to the syntax in [vs2vp.py](https://github.com/thurinj/specfem_tomo_helper/blob/main/specfem_tomo_helper/projection/vs2vp.py#L13)  the condition has to be any(vp) 

Thanks

**Comment by thurinj** [comment]
Fixed in the last commit, thanks for reporting. Thanks again @SeismoFelix.
